##
## EPITECH PROJECT, 2021
## sfsm
## File description:
## Makefile
##

all:
	make -C my
	make -C csfml

clean:
	make clean -C my
	make clean -C csfml

fclean:
	make fclean -C my
	make fclean -C csfml
	$(RM) *.a

re : fclean all
